# Generated by Django 6.0.5 on 2026-07-23 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djbcknd', '0002_alter_category_options_remove_product_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('SOLD', 'Sold Out'), ('RESERVED', 'Reserved')], default='AVAILABLE', max_length=15),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, help_text='Main city location of user', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='serviceproviderprofile',
            name='detailed_address',
            field=models.TextField(help_text='Exact home address for internal verification'),
        ),
        migrations.AlterField(
            model_name='serviceproviderprofile',
            name='provider_avatar',
            field=models.ImageField(help_text='Profile picture shown on Services Tab', upload_to='providers/avatars/'),
        ),
        migrations.AlterField(
            model_name='serviceproviderprofile',
            name='valid_id',
            field=models.ImageField(help_text='Government ID photo for admin verification only', upload_to='providers/ids/'),
        ),
    ]
