# Generated by Django 6.0.5 on 2026-07-27 02:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djbcknd', '0003_alter_product_status_alter_profile_city_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceproviderprofile',
            name='admin_notes',
            field=models.TextField(blank=True, help_text="Internal notes for admin review (e.g., 'ID verified', 'Blurry photo').", null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='serviceproviderprofile',
            name='verified_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when approved by Admin', null=True),
        ),
    ]
