# Generated by Django 5.2.17 on 2026-09-04 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djbcknd', '0007_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='service_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
