# Generated by Django 5.2.17 on 2026-09-20 05:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djbcknd', '0008_notification_service_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(db_index=True, editable=False, help_text='Unique internal reference number para sa reconciliation at PayMongo metadata', max_length=50, unique=True)),
                ('transaction_type', models.CharField(choices=[('BUY_AND_SELL', 'Buy and Sell'), ('SERVICES', 'Services')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Eksaktong halaga sa Pesos (e.g., 2500.00)', max_digits=10)),
                ('status', models.CharField(choices=[('HOLD', 'Hold / Pending Payment'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled'), ('DISPUTED', 'Under Dispute / May Reklamo'), ('REFUNDED', 'Refunded')], default='HOLD', max_length=20)),
                ('paymongo_checkout_id', models.CharField(blank=True, db_index=True, max_length=250, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('client_reason', models.TextField(blank=True, help_text='Reklamo o paliwanag ng Client/Buyer', null=True)),
                ('client_proof_image', models.ImageField(blank=True, null=True, upload_to='cancellation_proofs/client/')),
                ('provider_counter_reason', models.TextField(blank=True, help_text='Depensa o apela ng Provider/Seller', null=True)),
                ('provider_proof_image', models.ImageField(blank=True, null=True, upload_to='cancellation_proofs/provider/')),
                ('dispute_deadline', models.DateTimeField(blank=True, help_text='Palugit (5-7 days) para sa pagtugon ng kabilang panig bago mag-auto resolve', null=True)),
                ('auto_resolved', models.BooleanField(default=False, help_text='Flag kung ang background task ang nag-resolve ng dispute dahil walang sagot')),
                ('admin_decision', models.CharField(choices=[('PENDING', 'Pending Admin Review'), ('FAVOR_CLIENT', 'Favor to Client (Refund)'), ('FAVOR_PROVIDER', 'Favor to Provider/Seller (Release Payment)')], default='PENDING', help_text='Pinal na desisyon ng Admin kung kanino mapupunta ang pondo', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Rason o paliwanag ng Admin sa kanyang desisyon', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancelled_by', models.ForeignKey(blank=True, help_text='User o Provider na nag-initiate ng cancellation/dispute', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_cancellations', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, help_text='Link sa Buy & Sell product (null kung Services transaction)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_transactions', to='djbcknd.product')),
                ('service', models.ForeignKey(blank=True, help_text='Link sa Service booking (null kung Buy & Sell transaction)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_transactions', to='djbcknd.service')),
                ('user', models.ForeignKey(help_text='Ang nag-checkout o nagbayad', on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment Transaction',
                'verbose_name_plural': 'Payment Transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
