# Generated by Django 5.2.17 on 2026-09-20 07:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djbcknd', '0009_paymenttransaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='checkout_url_cache',
            field=models.URLField(blank=True, help_text='Cached PayMongo checkout_url, returned again on duplicate requests', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='idempotency_key',
            field=models.CharField(blank=True, db_index=True, help_text='Deterministic hash (user+product+amount) used to detect duplicate checkout requests', max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='admin_decision',
            field=models.CharField(choices=[('PENDING', 'Pending Admin Review'), ('FAVOR_CLIENT', 'Favor to Client (Refund)'), ('FAVOR_PROVIDER', 'Favor to Provider/Seller (Release Payment)')], default='PENDING', help_text='Final decision of Admin who will receive the funds', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='admin_notes',
            field=models.TextField(blank=True, help_text="Reason or explanation of Admin's decision", null=True),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Exact amount of peso (e.g., 2500.00)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='auto_resolved',
            field=models.BooleanField(default=False, help_text='Flag the background task resolved the dispute because no response'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, help_text='User or Provider who initiated the cancellation/dispute', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_cancellations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='client_reason',
            field=models.TextField(blank=True, help_text='Complaint or reason of Client/Buyer', null=True),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='dispute_deadline',
            field=models.DateTimeField(blank=True, help_text='Response Window (5-7 days) for response of both users', null=True),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='product',
            field=models.ForeignKey(blank=True, help_text='Link for Buy & Sell product (null if Services transaction)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_transactions', to='djbcknd.product'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='provider_counter_reason',
            field=models.TextField(blank=True, help_text='Appeal of Provider/Seller', null=True),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='reference_number',
            field=models.CharField(db_index=True, editable=False, help_text='Unique internal reference number for reconciliation and PayMongo metadata', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='service',
            field=models.ForeignKey(blank=True, help_text='Link for Service booking (null if Buy & Sell transaction)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_transactions', to='djbcknd.service'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='user',
            field=models.ForeignKey(help_text='The user who checked out or paid', on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='paymenttransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'HOLD'), ('transaction_type', 'BUY_AND_SELL')), fields=('user', 'product'), name='unique_hold_buy_and_sell_per_user_product'),
        ),
        migrations.AddConstraint(
            model_name='paymenttransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'HOLD'), ('transaction_type', 'SERVICES')), fields=('user', 'service'), name='unique_hold_service_per_user_service'),
        ),
    ]
