# Generated by Django 5.2.17 on 2026-09-24 04:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djbcknd', '0010_paymenttransaction_checkout_url_cache_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='released_at',
            field=models.DateTimeField(blank=True, help_text='Kailan i-release ang bayad papunta sa seller (manual o auto)', null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='released_by',
            field=models.ForeignKey(blank=True, help_text='Admin na nag-release ng bayad (null kung auto-release)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='released_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='status',
            field=models.CharField(choices=[('HOLD', 'Hold / Pending Payment'), ('PAID', 'Paid / Held in Escrow'), ('RELEASED', 'Released to Seller'), ('CANCELLED', 'Cancelled'), ('DISPUTED', 'Under Dispute'), ('REFUNDED', 'Refunded')], default='HOLD', max_length=20),
        ),
    ]
