"""
Django settings for bcknd project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""


import os
from pathlib import Path
import ssl
import certifi
from decouple import config


# ==========================================
# ⚙️ PATHS & CORE SETTINGS
# ==========================================
BASE_DIR = Path(__file__).resolve().parent.parent


# SECURITY WARNING: Don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)  # 🔧 CHANGED: default False (dati True) — fail-safe

ALLOWED_HOSTS = config(
    'ALLOWED_HOSTS',
    default='127.0.0.1,localhost',
    cast=lambda v: [s.strip() for s in v.split(',')]
)

# SECURITY WARNING: Keep secret key hidden in production using .env
SECRET_KEY = config('SECRET_KEY')

# PayMongo Credentials
PAYMONGO_PUBLIC_KEY = config('PAYMONGO_PUBLIC_KEY', default='')
PAYMONGO_SECRET_KEY = config('PAYMONGO_SECRET_KEY', default='')


# ==========================================
# 📦 INSTALLED APPS
# ==========================================
INSTALLED_APPS = [
    # Built-in Django Apps
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party Apps
    'corsheaders',
    'rest_framework',
    'rest_framework_simplejwt',          
    'rest_framework_simplejwt.token_blacklist',
    'channels',

    # Local Apps
    'djbcknd',
    'chatapp',
    'paymongo',
]


# ==========================================
# 🛡️ MIDDLEWARE
# ==========================================
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # Must be as high as possible
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


# ==========================================
# 🌐 URLS, TEMPLATES, & APPLICATIONS
# ==========================================
ROOT_URLCONF = 'bcknd.urls'
WSGI_APPLICATION = 'bcknd.wsgi.application'
ASGI_APPLICATION = 'bcknd.asgi.application'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


# ==========================================
# 🗄️ DATABASES & ROUTING
# ==========================================
DATABASES = {
    # Main Relational Database (PostgreSQL)
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('DB_NAME', default='dvstacks'),
        'USER': config('DB_USER', default='postgres'),
        'PASSWORD': config('DB_PASSWORD'),
        'HOST': config('DB_HOST', default='localhost'),
        'PORT': config('DB_PORT', default='5432'),
    },
    # Secondary Document Database (MongoDB)
    'mongodb': {
        'ENGINE': 'django_mongodb_backend',
        'NAME': config('MONGO_DB_NAME', default='servicemarket_db'),
        'HOST': config('MONGO_URI'),
    }
}

DATABASE_ROUTERS = ['bcknd.db_routers.MongoRouter']


# ==========================================
# 🔴 CHANNELS & REDIS (For Real-time Chat)
# ==========================================
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [{
                "address": config('REDIS_URL'),
                "ssl_ca_certs": certifi.where(),
                "socket_timeout": None,       
                "socket_keepalive": True,     
                "retry_on_timeout": True,       
                "health_check_interval": 30,
            }],
        },
    },
}


# ==========================================
# 🔐 REST FRAMEWORK & SECURITY
# ==========================================
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'djbcknd.authentication.CustomJWTAuthentication',
    ),
   
    'DEFAULT_THROTTLE_RATES': {
        'anon': '10/min',
    },
}

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# ==========================================
# 🌐 CORS CONFIGURATION
# ==========================================
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
]

CORS_ALLOW_CREDENTIALS = True

SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SAMESITE = 'Lax'

# 🔧 CHANGED: idinagdag — production-only hardening (hindi active kapag DEBUG=True,
# para hindi ka mablock habang naglo-localhost na walang HTTPS)
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True


# ==========================================
# 🌐 INTERNATIONALIZATION
# ==========================================
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# ==========================================
# 📁 STATIC & MEDIA FILES
# ==========================================
STATIC_URL = 'static/'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

DATABASE_ROUTERS = ['chatapp.db_router.MongoRouter']