"""
Django settings for bcknd project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""


import os
from pathlib import Path
import ssl
import certifi
from decouple import config

# ==========================================
# ⚙️ PATHS & CORE SETTINGS
# ==========================================
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: Keep secret key hidden in production using .env
SECRET_KEY = 'django-insecure-iu51hq+@gu6jew+#r2cvyis0-!3#g(44!q$x=#b9(pb9@gmoqr'

# SECURITY WARNING: Don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = config(
    'ALLOWED_HOSTS', 
    default='127.0.0.1,localhost', 
    cast=lambda v: [s.strip() for s in v.split(',')]
)


# ==========================================
# 📦 INSTALLED APPS
# ==========================================
INSTALLED_APPS = [
    # ASGI Server (Daphne MUST be first before staticfiles)
    'daphne',

    # Built-in Django Apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party Apps
    'corsheaders',
    'rest_framework',
    'channels',

    # Local Apps
    'djbcknd',
    'chatapp',
]


# ==========================================
# 🛡️ MIDDLEWARE
# ==========================================
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # Must be as high as possible
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


# ==========================================
# 🌐 URLS, TEMPLATES, & APPLICATIONS
# ==========================================
ROOT_URLCONF = 'bcknd.urls'
WSGI_APPLICATION = 'bcknd.wsgi.application'
ASGI_APPLICATION = 'bcknd.asgi.application'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


# ==========================================
# 🗄️ DATABASES & ROUTING
# ==========================================
DATABASES = {
    # Main Relational Database (PostgreSQL)
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('DB_NAME', default='dvstacks'),
        'USER': config('DB_USER', default='postgres'),
        'PASSWORD': config('DB_PASSWORD', default='12345'),
        'HOST': config('DB_HOST', default='localhost'),
        'PORT': config('DB_PORT', default='5432'),
    },
    # Secondary Document Database (MongoDB)
    'mongodb': {
        'ENGINE': 'django_mongodb_backend',
        'NAME': config('MONGO_DB_NAME', default='servicemarket_db'),
        'HOST': config('MONGO_URI', default='mongodb+srv://yemsz07_db_user:R1rCzgUsSOUhICJX@cluster0.85vsamp.mongodb.net/?appName=Cluster0'),
    }
}

DATABASE_ROUTERS = ['bcknd.db_routers.MongoRouter']


# ==========================================
# 🔴 CHANNELS & REDIS (For Real-time Chat)
# ==========================================
# Using in-memory channel layer for development (no Redis required)
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer',
    },
}


# ==========================================
# 🔐 REST FRAMEWORK & SECURITY
# ==========================================
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'djbcknd.authentication.CustomJWTAuthentication',
    ),
}

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# ==========================================
# 🌐 CORS CONFIGURATION
# ==========================================
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
]

CORS_ALLOW_CREDENTIALS = True


# ==========================================
# 🌐 INTERNATIONALIZATION
# ==========================================
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# ==========================================
# 📁 STATIC & MEDIA FILES
# ==========================================
STATIC_URL = 'static/'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

DATABASE_ROUTERS = ['chatapp.db_router.MongoRouter']